-- Model bazli tedarikci gunluk kapasite tablosu
-- Ayni tedarikci icin her modelde farkli kapasite tutulur.

CREATE TABLE IF NOT EXISTS public.tedarikci_model_kapasiteleri (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firma_id text NOT NULL,
  tedarikci_id text NOT NULL,
  model_id text NOT NULL,
  gunluk_kapasite numeric(12,2) NOT NULL CHECK (gunluk_kapasite > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tmk_firma_tedarikci_model
  ON public.tedarikci_model_kapasiteleri (firma_id, tedarikci_id, model_id);

CREATE INDEX IF NOT EXISTS idx_tmk_firma
  ON public.tedarikci_model_kapasiteleri (firma_id);

COMMENT ON TABLE public.tedarikci_model_kapasiteleri
  IS 'Tedarikci-model bazli gunluk uretim kapasitesi';

COMMENT ON COLUMN public.tedarikci_model_kapasiteleri.gunluk_kapasite
  IS 'Gunluk uretim kapasitesi (adet/gun)';

-- PostgREST schema cache yenileme
NOTIFY pgrst, 'reload schema';
