-- Dispatch invoice (sevk irsaliyesi) schema for inter-stage shipments
-- Run this migration in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public.sevk_irsaliyeleri (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firma_id text NOT NULL,
  irsaliye_no text NOT NULL,
  kaynak_asama text NOT NULL,
  hedef_asama text NOT NULL,
  kaynak_tablo text,
  kaynak_kayit_id text,
  model_id text NOT NULL,
  sevk_adedi integer NOT NULL CHECK (sevk_adedi > 0),
  hedef_tedarikci_id bigint,
  sevk_tarihi timestamptz NOT NULL DEFAULT now(),
  durum text NOT NULL DEFAULT 'onaylandi',
  notlar text,
  idempotency_key text,
  created_by text,
  onaylayan_id text,
  onay_tarihi timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sevk_irsaliye_no
  ON public.sevk_irsaliyeleri (firma_id, irsaliye_no);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sevk_irsaliye_idempotency
  ON public.sevk_irsaliyeleri (firma_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_sevk_irsaliyeleri_firma_tarih
  ON public.sevk_irsaliyeleri (firma_id, sevk_tarihi DESC);

CREATE TABLE IF NOT EXISTS public.sevk_irsaliye_kalemleri (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  irsaliye_id bigint NOT NULL REFERENCES public.sevk_irsaliyeleri(id) ON DELETE CASCADE,
  firma_id text NOT NULL,
  model_id text,
  beden_kodu text,
  koli_adedi integer,
  adet integer NOT NULL CHECK (adet > 0),
  birim text NOT NULL DEFAULT 'adet',
  aciklama text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_sevk_irsaliye_kalemleri_firma
  ON public.sevk_irsaliye_kalemleri (firma_id, irsaliye_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'sevk_irsaliyeleri'
  ) THEN
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'sevk_irsaliyeleri'
        AND column_name = 'kaynak_kayit_id'
        AND data_type <> 'text'
    ) THEN
      ALTER TABLE public.sevk_irsaliyeleri
        ALTER COLUMN kaynak_kayit_id TYPE text USING kaynak_kayit_id::text;
    END IF;

    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'sevk_irsaliyeleri'
        AND column_name = 'model_id'
        AND data_type <> 'text'
    ) THEN
      ALTER TABLE public.sevk_irsaliyeleri
        ALTER COLUMN model_id TYPE text USING model_id::text;
    END IF;
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'sevk_irsaliye_kalemleri'
  ) THEN
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'sevk_irsaliye_kalemleri'
        AND column_name = 'model_id'
        AND data_type <> 'text'
    ) THEN
      ALTER TABLE public.sevk_irsaliye_kalemleri
        ALTER COLUMN model_id TYPE text USING model_id::text;
    END IF;
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'sevkiyat_kayitlari'
  ) THEN
    ALTER TABLE public.sevkiyat_kayitlari
      ADD COLUMN IF NOT EXISTS firma_id text,
      ADD COLUMN IF NOT EXISTS model_id text,
      ADD COLUMN IF NOT EXISTS kalite_kontrol_id text,
      ADD COLUMN IF NOT EXISTS onceki_asama text,
      ADD COLUMN IF NOT EXISTS hedef_asama text,
      ADD COLUMN IF NOT EXISTS hedef_tedarikci_id bigint,
      ADD COLUMN IF NOT EXISTS alinan_adet integer DEFAULT 0,
      ADD COLUMN IF NOT EXISTS sevk_edilen_adet integer DEFAULT 0,
      ADD COLUMN IF NOT EXISTS kalan_adet integer DEFAULT 0,
      ADD COLUMN IF NOT EXISTS durum text DEFAULT 'beklemede',
      ADD COLUMN IF NOT EXISTS alis_tarihi timestamptz DEFAULT now(),
      ADD COLUMN IF NOT EXISTS sevk_tarihi timestamptz,
      ADD COLUMN IF NOT EXISTS tamamlanma_tarihi timestamptz,
      ADD COLUMN IF NOT EXISTS beden_detaylari jsonb,
      ADD COLUMN IF NOT EXISTS notlar text,
      ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'sevkiyat_kayitlari'
        AND column_name = 'uretim_kaydi_id'
        AND is_nullable = 'NO'
    ) THEN
      ALTER TABLE public.sevkiyat_kayitlari
        ALTER COLUMN uretim_kaydi_id DROP NOT NULL;
    END IF;

    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'sevkiyat_kayitlari'
        AND column_name = 'sevkiyat_personeli_id'
        AND is_nullable = 'NO'
    ) THEN
      ALTER TABLE public.sevkiyat_kayitlari
        ALTER COLUMN sevkiyat_personeli_id DROP NOT NULL;
    END IF;

    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'sevkiyat_kayitlari'
        AND column_name = 'hedef_atolye_id'
        AND is_nullable = 'NO'
    ) THEN
      ALTER TABLE public.sevkiyat_kayitlari
        ALTER COLUMN hedef_atolye_id DROP NOT NULL;
    END IF;
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'sevkiyat_kayitlari'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sevkiyat_kayitlari'
      AND policyname = 'sevkiyat_kayitlari_insert_compat'
  ) THEN
    EXECUTE '
      CREATE POLICY sevkiyat_kayitlari_insert_compat
      ON public.sevkiyat_kayitlari
      FOR INSERT
      WITH CHECK (auth.uid() IS NOT NULL)
    ';
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'sevkiyat_detaylari'
  ) THEN
    ALTER TABLE public.sevkiyat_detaylari
      ADD COLUMN IF NOT EXISTS irsaliye_id bigint,
      ADD COLUMN IF NOT EXISTS irsaliye_no text,
      ADD COLUMN IF NOT EXISTS beden_detaylari jsonb;
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'kalite_kontrol_atamalari'
  ) THEN
    ALTER TABLE public.kalite_kontrol_atamalari
      ADD COLUMN IF NOT EXISTS beden_detaylari jsonb;
  END IF;
END;
$$;

NOTIFY pgrst, 'reload schema';
