-- Test modelleri ekle
INSERT INTO triko_takip (
  marka,
  item_no,
  model_adi,
  sezon,
  koleksiyon,
  urun_kategorisi,
  triko_tipi,
  cinsiyet,
  yas_grubu,
  ana_iplik_turu,
  iplik_karisimi,
  ana_renkler,
  bedenler,
  toplam_adet,
  siparis_tarihi,
  termin_tarihi,
  durum,
  tamamlandi,
  created_at
) VALUES 
(
  'AKARORME',
  'MODEL001',
  'Klasik V Yaka Kazak',
  '2025 Kış',
  'Klasik Serisi',
  'Kazak',
  'Düz Örgü',
  'Unisex',
  'Yetişkin',
  'Akrilik',
  '%60 Akrilik %40 Pamuk',
  ARRAY['Lacivert', 'Siyah', 'Gri'],
  '{"XS": 10, "S": 20, "M": 30, "L": 25, "XL": 15}'::jsonb,
  100,
  '2025-11-01',
  '2025-12-15',
  'Beklemede',
  false,
  NOW()
),
(
  'AKARORME', 
  'MODEL002',
  'Balıkçı Yaka Triko',
  '2025 Kış',
  'Trend Serisi',
  'Triko',
  'Örgü',
  'Kadın',
  'Yetişkin',
  'Yün',
  '%70 Yün %30 Pamuk',
  ARRAY['Bordo', 'Kahverengi', 'Krem'],
  '{"S": 15, "M": 25, "L": 20, "XL": 10}'::jsonb,
  70,
  '2025-11-05',
  '2025-12-20',
  'Beklemede',
  false,
  NOW()
),
(
  'AKARORME',
  'MODEL003', 
  'Fermuarlı Hırka',
  '2025 İlkbahar',
  'Spor Serisi',
  'Hırka',
  'İnce Örgü',
  'Erkek',
  'Yetişkin',
  'Pamuk',
  '%100 Pamuk',
  ARRAY['Mavi', 'Yeşil', 'Beyaz'],
  '{"M": 20, "L": 30, "XL": 20, "XXL": 10}'::jsonb,
  80,
  '2025-11-10',
  '2025-12-30',
  'Planlama',
  false,
  NOW()
)
ON CONFLICT (item_no) DO NOTHING;