-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.abonelik_odemeleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  abonelik_id uuid NOT NULL,
  tutar numeric NOT NULL,
  para_birimi character varying DEFAULT 'TRY'::character varying,
  odeme_tarihi timestamp with time zone DEFAULT now(),
  odeme_yontemi character varying,
  odeme_referans character varying,
  durum character varying DEFAULT 'basarili'::character varying,
  fatura_no character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT abonelik_odemeleri_pkey PRIMARY KEY (id),
  CONSTRAINT abonelik_odemeleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT abonelik_odemeleri_abonelik_id_fkey FOREIGN KEY (abonelik_id) REFERENCES public.firma_abonelikleri(id)
);
CREATE TABLE public.abonelik_planlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_kodu character varying NOT NULL UNIQUE,
  plan_adi character varying NOT NULL,
  aciklama text,
  aylik_ucret numeric NOT NULL DEFAULT 0,
  yillik_ucret numeric,
  max_kullanici integer,
  max_modul integer,
  dahil_moduller jsonb DEFAULT '[]'::jsonb,
  ozellikler jsonb DEFAULT '{}'::jsonb,
  aktif boolean DEFAULT true,
  sira_no integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT abonelik_planlari_pkey PRIMARY KEY (id)
);
CREATE TABLE public.aksesuar_bedenler (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aksesuar_id uuid NOT NULL,
  beden text NOT NULL,
  stok_miktari integer NOT NULL DEFAULT 0,
  durum text DEFAULT 'aktif'::text CHECK (durum = ANY (ARRAY['aktif'::text, 'pasif'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT aksesuar_bedenler_pkey PRIMARY KEY (id),
  CONSTRAINT aksesuar_bedenler_aksesuar_id_fkey FOREIGN KEY (aksesuar_id) REFERENCES public.aksesuarlar(id),
  CONSTRAINT aksesuar_bedenler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.aksesuar_hareketleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aksesuar_id uuid NOT NULL,
  hareket_tipi text NOT NULL CHECK (hareket_tipi = ANY (ARRAY['giris'::text, 'cikis'::text, 'transfer'::text, 'sayim'::text])),
  miktar numeric NOT NULL,
  kalan_miktar numeric,
  aciklama text,
  model_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT aksesuar_hareketleri_pkey PRIMARY KEY (id),
  CONSTRAINT aksesuar_hareketleri_aksesuar_id_fkey FOREIGN KEY (aksesuar_id) REFERENCES public.aksesuarlar(id),
  CONSTRAINT aksesuar_hareketleri_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.aksesuar_kullanim (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  aksesuar_id uuid NOT NULL,
  beden_id uuid,
  beden text,
  musteri_id text,
  model_id uuid,
  miktar integer NOT NULL DEFAULT 0,
  islem_tipi text NOT NULL DEFAULT 'sarf'::text,
  aciklama text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aksesuar_kullanim_pkey PRIMARY KEY (id),
  CONSTRAINT aksesuar_kullanim_aksesuar_id_fkey FOREIGN KEY (aksesuar_id) REFERENCES public.aksesuarlar(id),
  CONSTRAINT aksesuar_kullanim_beden_id_fkey FOREIGN KEY (beden_id) REFERENCES public.aksesuar_bedenler(id),
  CONSTRAINT aksesuar_kullanim_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.aksesuar_stok_hareketleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aksesuar_beden_id uuid NOT NULL,
  hareket_tipi text NOT NULL CHECK (hareket_tipi = ANY (ARRAY['giris'::text, 'cikis'::text, 'duzeltme'::text, 'fire'::text, 'sayim'::text, 'sarf'::text])),
  miktar integer NOT NULL,
  onceki_stok integer NOT NULL,
  yeni_stok integer NOT NULL,
  model_id uuid,
  siparis_no text,
  fatura_no text,
  aciklama text,
  kullanici_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  firma_id uuid,
  tedarikci_id integer,
  tedarikci_adi text,
  CONSTRAINT aksesuar_stok_hareketleri_pkey PRIMARY KEY (id),
  CONSTRAINT aksesuar_stok_hareketleri_tedarikci_id_fkey FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT aksesuar_stok_hareketleri_aksesuar_beden_id_fkey FOREIGN KEY (aksesuar_beden_id) REFERENCES public.aksesuar_bedenler(id),
  CONSTRAINT aksesuar_stok_hareketleri_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.aksesuarlar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ad text NOT NULL,
  kategori text,
  beden text,
  renk text,
  miktar numeric DEFAULT 0,
  birim text DEFAULT 'adet'::text,
  birim_fiyat numeric,
  para_birimi text DEFAULT 'TL'::text CHECK (para_birimi = ANY (ARRAY['TL'::text, 'USD'::text, 'EUR'::text])),
  toplam_deger numeric,
  tedarikci_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  aksesuar_kodu character varying UNIQUE,
  resim_url text,
  sku text UNIQUE,
  renk_kodu text,
  minimum_stok integer DEFAULT 10,
  malzeme text,
  marka text,
  aciklama text,
  durum text DEFAULT 'aktif'::text CHECK (durum = ANY (ARRAY['aktif'::text, 'pasif'::text])),
  firma_id uuid NOT NULL,
  CONSTRAINT aksesuarlar_pkey PRIMARY KEY (id),
  CONSTRAINT aksesuarlar_tedarikci_id_fkey FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT aksesuarlar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.atolye_kapasite_takip (
  id integer NOT NULL DEFAULT nextval('atolye_kapasite_takip_id_seq'::regclass),
  atolye_id integer NOT NULL,
  tarih date NOT NULL,
  toplam_kapasite integer DEFAULT 100,
  kullanilan_kapasite integer DEFAULT 0,
  bekleyen_is_adedi integer DEFAULT 0,
  tamamlanan_is_adedi integer DEFAULT 0,
  ortalama_islem_suresi interval,
  kalite_basari_orani numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT atolye_kapasite_takip_pkey PRIMARY KEY (id),
  CONSTRAINT atolye_kapasite_takip_atolye_id_fkey FOREIGN KEY (atolye_id) REFERENCES public.atolyeler(id)
);
CREATE TABLE public.atolyeler (
  id integer NOT NULL DEFAULT nextval('atolyeler_id_seq'::regclass),
  atolye_adi character varying NOT NULL,
  atolye_turu character varying NOT NULL,
  adres text,
  telefon character varying,
  email character varying,
  kapasitesi integer DEFAULT 100,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT atolyeler_pkey PRIMARY KEY (id),
  CONSTRAINT atolyeler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.beden_tanimlari (
  id integer NOT NULL DEFAULT nextval('beden_tanimlari_id_seq'::regclass),
  beden_kodu character varying NOT NULL UNIQUE,
  beden_adi character varying,
  sira_no integer DEFAULT 0,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT beden_tanimlari_pkey PRIMARY KEY (id),
  CONSTRAINT beden_tanimlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.bildirimler (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  baslik text NOT NULL,
  mesaj text NOT NULL,
  tip text NOT NULL CHECK (tip = ANY (ARRAY['atama_bekliyor'::text, 'atama_onaylandi'::text, 'atama_reddedildi'::text, 'uretim_tamamlandi'::text, 'kalite_onay'::text, 'kalite_red'::text, 'sevkiyat_hazir'::text, 'genel'::text])),
  model_id uuid,
  uretim_kaydi_id uuid,
  asama text CHECK (asama = ANY (ARRAY['orgu'::text, 'konfeksiyon'::text, 'yikama'::text, 'nakis'::text, 'ilik_dugme'::text, 'utu'::text, 'diger'::text])),
  okundu boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  atama_id uuid,
  firma_id uuid NOT NULL,
  CONSTRAINT bildirimler_pkey PRIMARY KEY (id),
  CONSTRAINT bildirimler_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT bildirimler_uretim_kaydi_id_fkey FOREIGN KEY (uretim_kaydi_id) REFERENCES public.uretim_kayitlari(id),
  CONSTRAINT bildirimler_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT bildirimler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT bildirimler_atama_id_fkey FOREIGN KEY (atama_id) REFERENCES public.uretim_kayitlari(id)
);
CREATE TABLE public.bordro (
  id integer NOT NULL DEFAULT nextval('bordro_id_seq'::regclass),
  personel_id uuid,
  donem character varying NOT NULL,
  temel_maas numeric DEFAULT 0,
  mesai_ucreti numeric DEFAULT 0,
  prim numeric DEFAULT 0,
  kesintiler numeric DEFAULT 0,
  net_maas numeric DEFAULT 0,
  odeme_tarihi date,
  aciklama text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  yil integer,
  ay integer,
  brut_maas numeric DEFAULT 0,
  vergi numeric DEFAULT 0,
  sgk numeric DEFAULT 0,
  damga_vergisi numeric DEFAULT 0,
  gelir_vergisi numeric DEFAULT 0,
  toplam_kesinti numeric DEFAULT 0,
  net_odeme numeric DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT bordro_pkey PRIMARY KEY (id),
  CONSTRAINT bordro_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.ceki_listesi (
  id integer NOT NULL DEFAULT nextval('ceki_listesi_id_seq'::regclass),
  model_id uuid,
  koli_no character varying,
  koli_adedi integer DEFAULT 1,
  adet integer,
  paketleme_tarihi timestamp with time zone DEFAULT now(),
  gonderim_durumu character varying DEFAULT 'bekliyor'::character varying,
  gonderim_tarihi timestamp with time zone,
  alici_bilgisi text,
  kargo_firmasi character varying,
  takip_no character varying,
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  beden_kodu character varying,
  adet_per_koli integer DEFAULT 10,
  is_mix_koli boolean DEFAULT false,
  mix_beden_detay jsonb,
  firma_id uuid NOT NULL,
  CONSTRAINT ceki_listesi_pkey PRIMARY KEY (id),
  CONSTRAINT ceki_listesi_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT ceki_listesi_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.destek_talepleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  user_id uuid NOT NULL,
  konu text NOT NULL,
  aciklama text NOT NULL,
  durum text NOT NULL DEFAULT 'acik'::text CHECK (durum = ANY (ARRAY['acik'::text, 'inceleniyor'::text, 'cevaplandi'::text, 'kapali'::text])),
  onem_seviyesi text DEFAULT 'normal'::text CHECK (onem_seviyesi = ANY (ARRAY['dusuk'::text, 'normal'::text, 'yuksek'::text, 'kritik'::text])),
  cevap text,
  cevaplayan_id uuid,
  cevap_tarihi timestamp with time zone,
  kapatma_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT destek_talepleri_pkey PRIMARY KEY (id),
  CONSTRAINT destek_talepleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT destek_talepleri_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT destek_talepleri_cevaplayan_id_fkey FOREIGN KEY (cevaplayan_id) REFERENCES auth.users(id)
);
CREATE TABLE public.dokuma_atamalari (
  id integer NOT NULL DEFAULT nextval('dokuma_atamalari_id_seq'::regclass),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  durum text NOT NULL DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  notlar text,
  atama_tarihi timestamp with time zone DEFAULT now(),
  baslama_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  adet integer,
  talep_edilen_adet integer,
  tamamlanan_adet integer,
  musteri_adi text,
  tedarikci_id integer,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  uretim_baslangic_tarihi timestamp with time zone,
  uretici_notlari text,
  kabul_edilen_adet integer,
  planlanan_bitis_tarihi timestamp with time zone,
  fire_adet integer DEFAULT 0,
  firma_id uuid NOT NULL,
  CONSTRAINT dokuma_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT dokuma_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT dokuma_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT fk_dokuma_atamalari_tedarikci FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT dokuma_atamalari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.dokuma_atamalari_backup (
  id integer,
  model_id integer,
  atanan_kullanici_id uuid,
  durum text,
  notlar text,
  atama_tarihi timestamp with time zone,
  baslama_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.dokuma_beden_takip (
  id integer NOT NULL DEFAULT nextval('dokuma_beden_takip_id_seq'::regclass),
  atama_id integer NOT NULL,
  model_id uuid NOT NULL,
  beden_kodu character varying NOT NULL,
  hedef_adet integer NOT NULL DEFAULT 0,
  uretilen_adet integer DEFAULT 0,
  kabul_edilen_adet integer DEFAULT 0,
  fire_adet integer DEFAULT 0,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  guncelleme_tarihi timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT dokuma_beden_takip_pkey PRIMARY KEY (id),
  CONSTRAINT dokuma_beden_takip_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT dokuma_beden_takip_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.donemler (
  id integer NOT NULL DEFAULT nextval('donemler_id_seq'::regclass),
  yil integer NOT NULL,
  ay integer NOT NULL CHECK (ay >= 1 AND ay <= 12),
  donem_adi character varying NOT NULL UNIQUE,
  durum character varying DEFAULT 'aktif'::character varying CHECK (durum::text = ANY (ARRAY['aktif'::character varying::text, 'tamamlandi'::character varying::text, 'arsivlendi'::character varying::text])),
  olusturan_kullanici_id uuid,
  olusturulma_tarihi timestamp without time zone DEFAULT now(),
  guncellenme_tarihi timestamp without time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT donemler_pkey PRIMARY KEY (id),
  CONSTRAINT donemler_olusturan_kullanici_id_fkey FOREIGN KEY (olusturan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT donemler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.dosya_paylasimlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dosya_id uuid,
  paylasan_kullanici_id uuid,
  hedef_kullanici_id uuid,
  izin_turu character varying DEFAULT 'read'::character varying,
  paylasim_tarihi timestamp with time zone DEFAULT now(),
  aktif boolean DEFAULT true,
  CONSTRAINT dosya_paylasimlari_pkey PRIMARY KEY (id),
  CONSTRAINT fk_dosya FOREIGN KEY (dosya_id) REFERENCES public.dosyalar(id)
);
CREATE TABLE public.dosyalar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ad character varying NOT NULL,
  dosya_turu character varying DEFAULT 'pdf'::character varying,
  boyut bigint DEFAULT 0,
  yol text NOT NULL,
  ust_klasor_id uuid,
  aciklama text,
  olusturan_kullanici_id uuid,
  olusturma_tarihi timestamp with time zone DEFAULT now(),
  guncelleme_tarihi timestamp with time zone DEFAULT now(),
  aktif boolean DEFAULT true,
  genel_erisim boolean DEFAULT false,
  son_erisim_tarihi timestamp with time zone,
  erisim_sayisi integer DEFAULT 0,
  mime_type character varying,
  firma_id uuid NOT NULL,
  CONSTRAINT dosyalar_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ust_klasor FOREIGN KEY (ust_klasor_id) REFERENCES public.dosyalar(id),
  CONSTRAINT dosyalar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.fatura_kalemleri (
  id integer NOT NULL DEFAULT nextval('fatura_kalemleri_id_seq'::regclass),
  fatura_id integer,
  model_id uuid,
  urun_adi character varying NOT NULL,
  urun_kodu character varying,
  miktar numeric NOT NULL,
  birim character varying DEFAULT 'adet'::character varying,
  birim_fiyat numeric NOT NULL,
  iskonto_orani numeric DEFAULT 0,
  iskonto_tutari numeric DEFAULT 0,
  kdv_orani numeric DEFAULT 20,
  kdv_tutari numeric DEFAULT 0,
  toplam_tutar numeric NOT NULL,
  aciklama text,
  olusturma_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  firma_id uuid NOT NULL,
  CONSTRAINT fatura_kalemleri_pkey PRIMARY KEY (id),
  CONSTRAINT fatura_kalemleri_fatura_id_fkey FOREIGN KEY (fatura_id) REFERENCES public.faturalar(fatura_id),
  CONSTRAINT fatura_kalemleri_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT fatura_kalemleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.faturalar (
  fatura_id integer NOT NULL DEFAULT nextval('faturalar_fatura_id_seq'::regclass),
  fatura_no character varying NOT NULL UNIQUE,
  fatura_turu character varying DEFAULT 'satis'::character varying,
  fatura_tarihi date NOT NULL,
  musteri_id integer,
  tedarikci_id integer,
  fatura_adres text NOT NULL,
  vergi_dairesi character varying,
  vergi_no character varying,
  ara_toplam_tutar numeric DEFAULT 0,
  kdv_tutari numeric DEFAULT 0,
  toplam_tutar numeric DEFAULT 0,
  durum character varying DEFAULT 'taslak'::character varying,
  aciklama text,
  vade_tarihi date,
  odeme_durumu character varying DEFAULT 'odenmedi'::character varying,
  odenen_tutar numeric DEFAULT 0,
  kur character varying DEFAULT 'TRY'::character varying,
  kur_orani numeric DEFAULT 1.0000,
  efatura_uuid character varying,
  efatura_tarihi timestamp without time zone,
  efatura_durum character varying,
  olusturma_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  guncelleme_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  olusturan_kullanici character varying,
  firma_id uuid NOT NULL,
  CONSTRAINT faturalar_pkey PRIMARY KEY (fatura_id),
  CONSTRAINT faturalar_musteri_id_fkey FOREIGN KEY (musteri_id) REFERENCES public.musteriler(id),
  CONSTRAINT faturalar_tedarikci_id_fkey FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT faturalar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.fire_kayitlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid,
  asama text NOT NULL,
  adet integer NOT NULL,
  tarih date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fire_kayitlari_pkey PRIMARY KEY (id),
  CONSTRAINT fire_kayitlari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.firma_abonelikleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  durum character varying DEFAULT 'deneme'::character varying CHECK (durum::text = ANY (ARRAY['aktif'::character varying, 'pasif'::character varying, 'deneme'::character varying, 'iptal'::character varying, 'odeme_bekleniyor'::character varying]::text[])),
  baslangic_tarihi timestamp with time zone DEFAULT now(),
  bitis_tarihi timestamp with time zone,
  deneme_bitis timestamp with time zone DEFAULT (now() + '14 days'::interval),
  odeme_periyodu character varying DEFAULT 'aylik'::character varying CHECK (odeme_periyodu::text = ANY (ARRAY['aylik'::character varying, 'yillik'::character varying]::text[])),
  son_odeme_tarihi timestamp with time zone,
  sonraki_odeme_tarihi timestamp with time zone,
  iptal_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT firma_abonelikleri_pkey PRIMARY KEY (id),
  CONSTRAINT firma_abonelikleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT firma_abonelikleri_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.abonelik_planlari(id)
);
CREATE TABLE public.firma_ayarlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  anahtar character varying NOT NULL,
  deger text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT firma_ayarlari_pkey PRIMARY KEY (id),
  CONSTRAINT firma_ayarlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.firma_davetleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  davet_eden_id uuid NOT NULL,
  email character varying NOT NULL,
  rol character varying DEFAULT 'kullanici'::character varying,
  davet_kodu character varying NOT NULL UNIQUE,
  durum character varying DEFAULT 'beklemede'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  gecerlilik_tarihi timestamp with time zone DEFAULT (now() + '7 days'::interval),
  CONSTRAINT firma_davetleri_pkey PRIMARY KEY (id),
  CONSTRAINT firma_davetleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT firma_davetleri_davet_eden_id_fkey FOREIGN KEY (davet_eden_id) REFERENCES auth.users(id)
);
CREATE TABLE public.firma_kullanicilari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rol character varying NOT NULL DEFAULT 'kullanici'::character varying,
  yetki_grubu jsonb DEFAULT '[]'::jsonb,
  aktif boolean DEFAULT true,
  davet_tarihi timestamp with time zone DEFAULT now(),
  katilim_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT firma_kullanicilari_pkey PRIMARY KEY (id),
  CONSTRAINT firma_kullanicilari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT firma_kullanicilari_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.firma_modulleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  modul_id uuid NOT NULL,
  aktif boolean DEFAULT true,
  aktivasyon_tarihi timestamp with time zone DEFAULT now(),
  bitis_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT firma_modulleri_pkey PRIMARY KEY (id),
  CONSTRAINT firma_modulleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT firma_modulleri_modul_id_fkey FOREIGN KEY (modul_id) REFERENCES public.modul_tanimlari(id)
);
CREATE TABLE public.firma_sayfa_yetkileri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  sayfa_kodu text NOT NULL,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT firma_sayfa_yetkileri_pkey PRIMARY KEY (id),
  CONSTRAINT firma_sayfa_yetkileri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.firma_uretim_modulleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  uretim_modul_id uuid NOT NULL,
  tekstil_dali text,
  aktif boolean DEFAULT true,
  aktivasyon_tarihi timestamp with time zone DEFAULT now(),
  bitis_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT firma_uretim_modulleri_pkey PRIMARY KEY (id),
  CONSTRAINT firma_uretim_modulleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT firma_uretim_modulleri_uretim_modul_id_fkey FOREIGN KEY (uretim_modul_id) REFERENCES public.uretim_modulleri(id)
);
CREATE TABLE public.firmalar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_adi character varying NOT NULL,
  firma_kodu character varying NOT NULL UNIQUE,
  vergi_no character varying,
  vergi_dairesi character varying,
  sicil_no character varying,
  sgk_sicil_no character varying,
  adres text,
  telefon character varying,
  email character varying,
  web character varying,
  logo_url text,
  yetkili character varying,
  iban character varying,
  banka character varying,
  sektor character varying DEFAULT 'tekstil'::character varying,
  faaliyet character varying,
  kurulus_yili integer,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT firmalar_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ilik_dugme_atamalari (
  id integer NOT NULL DEFAULT nextval('ilik_dugme_atamalari_id_seq'::regclass),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  durum text NOT NULL DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  atama_tarihi timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  uretim_baslangic_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  dugme_adedi integer,
  ilik_adedi integer,
  dugme_tipi text,
  notlar text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  tedarikci_id integer,
  adet integer,
  talep_edilen_adet integer,
  tamamlanan_adet integer,
  uretici_notlari text,
  kabul_edilen_adet integer,
  planlanan_bitis_tarihi timestamp with time zone,
  fire_adet integer DEFAULT 0,
  baslama_tarihi timestamp with time zone,
  hedef_adet integer DEFAULT 0,
  fire_dusulmus_adet integer DEFAULT 0,
  firma_id uuid NOT NULL,
  CONSTRAINT ilik_dugme_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT ilik_dugme_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT ilik_dugme_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT fk_ilik_dugme_atamalari_tedarikci FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT ilik_dugme_atamalari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.ilik_dugme_beden_takip (
  id integer NOT NULL DEFAULT nextval('ilik_dugme_beden_takip_id_seq'::regclass),
  atama_id integer NOT NULL,
  model_id uuid NOT NULL,
  beden_kodu character varying NOT NULL,
  hedef_adet integer NOT NULL DEFAULT 0,
  uretilen_adet integer DEFAULT 0,
  kabul_edilen_adet integer DEFAULT 0,
  fire_adet integer DEFAULT 0,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  guncelleme_tarihi timestamp with time zone DEFAULT now(),
  CONSTRAINT ilik_dugme_beden_takip_pkey PRIMARY KEY (id),
  CONSTRAINT ilik_dugme_beden_takip_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.iplik_hareketleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  iplik_id uuid NOT NULL,
  hareket_tipi text NOT NULL,
  miktar numeric NOT NULL,
  aciklama text,
  model_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  iplik_stok_id uuid,
  firma_id uuid NOT NULL,
  CONSTRAINT iplik_hareketleri_pkey PRIMARY KEY (id),
  CONSTRAINT iplik_hareketleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.iplik_siparisleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  siparis_no character varying NOT NULL,
  tedarikci_id integer,
  iplik_adi character varying,
  renk character varying,
  miktar numeric NOT NULL,
  birim character varying DEFAULT 'kg'::character varying,
  birim_fiyat numeric,
  para_birimi character varying DEFAULT 'TL'::character varying,
  toplam_tutar numeric,
  termin_tarihi date,
  siparis_tarihi timestamp with time zone NOT NULL DEFAULT now(),
  durum character varying DEFAULT 'beklemede'::character varying,
  aciklama text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  teslim_edildi_at timestamp with time zone,
  teslim_edildi boolean DEFAULT false,
  teslim_miktari numeric DEFAULT 0,
  teslim_tarihi date,
  lot_no text,
  kalite_durumu text DEFAULT 'beklemede'::text,
  teslim_yuzdesi numeric DEFAULT 0,
  marka text,
  orgu_firmasi_id integer,
  firma_id uuid NOT NULL,
  CONSTRAINT iplik_siparisleri_pkey PRIMARY KEY (id),
  CONSTRAINT iplik_siparisleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.iplik_stoklari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ad text NOT NULL,
  renk text,
  lot_no text,
  miktar numeric DEFAULT 0,
  birim text DEFAULT 'kg'::text,
  birim_fiyat numeric,
  para_birimi text DEFAULT 'TL'::text,
  toplam_deger numeric,
  tedarikci_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  aciklama text,
  firma_id uuid NOT NULL,
  CONSTRAINT iplik_stoklari_pkey PRIMARY KEY (id),
  CONSTRAINT iplik_stoklari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT iplik_stoklari_tedarikci_id_fkey FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id)
);
CREATE TABLE public.izinler (
  id integer NOT NULL DEFAULT nextval('izinler_id_seq'::regclass),
  izin_turu character varying NOT NULL,
  baslama_tarihi date NOT NULL,
  bitis_tarihi date NOT NULL,
  gun_sayisi integer NOT NULL,
  aciklama text,
  onay_durumu character varying DEFAULT 'beklemede'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  onaylayan_user_id uuid,
  onay_tarihi timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  baslangic date,
  durum character varying DEFAULT 'beklemede'::character varying,
  user_id uuid,
  bitis date,
  firma_id uuid NOT NULL,
  CONSTRAINT izinler_pkey PRIMARY KEY (id),
  CONSTRAINT izinler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.kalite_kontrol_atamalari (
  id integer NOT NULL DEFAULT nextval('kalite_kontrol_atamalari_id_seq'::regclass),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  durum text NOT NULL DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'beklemede'::text, 'kontrol_bekliyor'::text, 'kontrolde'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  atama_tarihi timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  kontrol_baslangic_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  kalite_notu integer CHECK (kalite_notu >= 1 AND kalite_notu <= 10),
  hatalar ARRAY,
  notlar text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  uretici_notlari text,
  onceki_asama text,
  onceki_atama_id uuid,
  kalite_sonucu text,
  kalite_notlari text,
  kalite_tarihi timestamp with time zone,
  kalite_personeli_id uuid,
  adet integer DEFAULT 0,
  planlanan_bitis_tarihi timestamp with time zone,
  kontrol_edilecek_adet integer,
  baslangic_tarihi timestamp with time zone,
  tamamlanma_tarihi timestamp with time zone,
  fire_adet integer DEFAULT 0,
  baslama_tarihi timestamp with time zone,
  talep_edilen_adet integer DEFAULT 0,
  kabul_edilen_adet integer DEFAULT 0,
  tamamlanan_adet integer DEFAULT 0,
  uretim_baslangic_tarihi timestamp with time zone,
  firma_id uuid NOT NULL,
  kaynak_atama_tablosu text,
  kaynak_atama_id bigint,
  idempotency_key text,
  beden_detaylari jsonb,
  CONSTRAINT kalite_kontrol_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT kalite_kontrol_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT kalite_kontrol_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT kalite_kontrol_atamalari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.kasa_banka_hareketleri (
  id integer NOT NULL DEFAULT nextval('kasa_banka_hareketleri_id_seq'::regclass),
  hesap_id integer,
  kasa_banka_id integer,
  hareket_tarihi date NOT NULL,
  hareket_tipi character varying DEFAULT 'giris'::character varying,
  islem_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  kategori character varying,
  aciklama text,
  giren_tutar numeric DEFAULT 0,
  cikan_tutar numeric DEFAULT 0,
  bakiye numeric DEFAULT 0,
  olusturma_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  firma_id uuid NOT NULL,
  CONSTRAINT kasa_banka_hareketleri_pkey PRIMARY KEY (id),
  CONSTRAINT kasa_banka_hareketleri_hesap_id_fkey FOREIGN KEY (hesap_id) REFERENCES public.kasa_banka_hesaplari(id),
  CONSTRAINT kasa_banka_hareketleri_kasa_banka_id_fkey FOREIGN KEY (kasa_banka_id) REFERENCES public.kasa_banka_hesaplari(id),
  CONSTRAINT kasa_banka_hareketleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.kasa_banka_hesaplari (
  id integer NOT NULL DEFAULT nextval('kasa_banka_hesaplari_id_seq'::regclass),
  hesap_adi character varying NOT NULL,
  hesap_no character varying,
  iban character varying,
  tip character varying DEFAULT 'banka'::character varying,
  durumu character varying DEFAULT 'aktif'::character varying,
  doviz_kodu character varying DEFAULT 'TRY'::character varying,
  bakiye numeric DEFAULT 0,
  olusturma_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  guncelleme_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  firma_id uuid NOT NULL,
  CONSTRAINT kasa_banka_hesaplari_pkey PRIMARY KEY (id),
  CONSTRAINT kasa_banka_hesaplari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.konfeksiyon_atamalari (
  id integer NOT NULL DEFAULT nextval('konfeksiyon_atamalari_id_seq'::regclass),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  durum text NOT NULL DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  atama_tarihi timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  uretim_baslangic_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  notlar text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  tedarikci_id integer,
  adet integer,
  talep_edilen_adet integer,
  tamamlanan_adet integer,
  uretici_notlari text,
  kabul_edilen_adet integer,
  planlanan_bitis_tarihi timestamp with time zone,
  fire_adet integer DEFAULT 0,
  baslama_tarihi timestamp with time zone,
  hedef_adet integer DEFAULT 0,
  fire_dusulmus_adet integer DEFAULT 0,
  firma_id uuid NOT NULL,
  CONSTRAINT konfeksiyon_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT konfeksiyon_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT konfeksiyon_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT fk_konfeksiyon_atamalari_tedarikci FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT konfeksiyon_atamalari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.konfeksiyon_atamalari_backup (
  id integer,
  model_id integer,
  atanan_kullanici_id uuid,
  atama_tarihi timestamp with time zone,
  durum text,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  uretim_baslangic_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  notlar text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.konfeksiyon_beden_takip (
  id integer NOT NULL DEFAULT nextval('konfeksiyon_beden_takip_id_seq'::regclass),
  atama_id integer NOT NULL,
  model_id uuid NOT NULL,
  beden_kodu character varying NOT NULL,
  hedef_adet integer NOT NULL DEFAULT 0,
  uretilen_adet integer DEFAULT 0,
  kabul_edilen_adet integer DEFAULT 0,
  fire_adet integer DEFAULT 0,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  guncelleme_tarihi timestamp with time zone DEFAULT now(),
  CONSTRAINT konfeksiyon_beden_takip_pkey PRIMARY KEY (id),
  CONSTRAINT konfeksiyon_beden_takip_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.kullanici_aktif_firma (
  user_id uuid NOT NULL,
  firma_id uuid NOT NULL,
  son_giris timestamp with time zone DEFAULT now(),
  CONSTRAINT kullanici_aktif_firma_pkey PRIMARY KEY (user_id),
  CONSTRAINT kullanici_aktif_firma_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT kullanici_aktif_firma_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.kullanici_sayfa_yetkileri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  user_id uuid NOT NULL,
  sayfa_kodu text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  duzenleme_yetkisi boolean NOT NULL DEFAULT false,
  silme_yetkisi boolean NOT NULL DEFAULT false,
  CONSTRAINT kullanici_sayfa_yetkileri_pkey PRIMARY KEY (id),
  CONSTRAINT kullanici_sayfa_yetkileri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.loglar (
  id integer NOT NULL DEFAULT nextval('loglar_id_seq'::regclass),
  kullanici_id uuid,
  islem character varying NOT NULL,
  detay text,
  ip_adres character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT loglar_pkey PRIMARY KEY (id),
  CONSTRAINT loglar_kullanici_id_fkey FOREIGN KEY (kullanici_id) REFERENCES auth.users(id)
);
CREATE TABLE public.maliyet_hesaplama (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  marka text,
  model text,
  ip_cinsi text,
  urun_gr numeric,
  iplik_kg_fiyati numeric,
  iplik_maliyeti numeric,
  orgu_suresi numeric,
  orgu_fiyati numeric,
  orgu_toplam_maliyet numeric,
  utu_maliyeti numeric,
  yikama_maliyeti numeric,
  boyama_maliyeti numeric,
  konfeksiyon_maliyeti numeric,
  aksesuar_maliyeti numeric,
  fermuar_maliyeti numeric,
  ilik_dugme_maliyeti numeric,
  genel_gider numeric,
  toplam_birim_maliyet numeric,
  para_birimi text DEFAULT 'TRY'::text,
  maliyet_notu text,
  firma_id uuid NOT NULL,
  CONSTRAINT maliyet_hesaplama_pkey PRIMARY KEY (id),
  CONSTRAINT maliyet_hesaplama_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT maliyet_hesaplama_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.mesai (
  id integer NOT NULL DEFAULT nextval('mesai_id_seq'::regclass),
  tarih date NOT NULL,
  mesai_saati numeric DEFAULT 0,
  saat_ucreti numeric DEFAULT 0,
  toplam_ucret numeric DEFAULT 0,
  aciklama text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  giris_saati time without time zone,
  cikis_saati time without time zone,
  saat numeric DEFAULT 0,
  fazla_mesai_saati numeric DEFAULT 0,
  onaylandi boolean DEFAULT false,
  onaylayan_user_id uuid,
  onay_tarihi timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  onay_durumu character varying,
  baslangic_saati time without time zone,
  bitis_saati time without time zone,
  mesai_turu character varying,
  mesai_ucret numeric,
  yemek_ucreti integer,
  carpan numeric,
  firma_id uuid NOT NULL,
  CONSTRAINT mesai_pkey PRIMARY KEY (id),
  CONSTRAINT mesai_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.migrasyon_durumu (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  adim_adi text NOT NULL,
  durum text NOT NULL DEFAULT 'beklemede'::text CHECK (durum = ANY (ARRAY['beklemede'::text, 'baslamis'::text, 'tamamlandi'::text, 'hata'::text])),
  hata_mesaji text,
  baslangic_tarihi timestamp with time zone DEFAULT now(),
  bitis_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT migrasyon_durumu_pkey PRIMARY KEY (id)
);
CREATE TABLE public.model_aksesuar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid,
  aksesuar_id uuid,
  miktar integer NOT NULL DEFAULT 1,
  adet_per_model integer DEFAULT 1,
  pozisyon text,
  zorunlu boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT model_aksesuar_pkey PRIMARY KEY (id),
  CONSTRAINT model_aksesuar_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT model_aksesuar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.model_aksesuar_bedenler (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid NOT NULL,
  aksesuar_beden_id uuid NOT NULL,
  kullanim_miktari numeric NOT NULL DEFAULT 1,
  zorunlu boolean DEFAULT true,
  kullanim_yeri text,
  sira_no integer,
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT model_aksesuar_bedenler_pkey PRIMARY KEY (id),
  CONSTRAINT model_aksesuar_bedenler_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT model_aksesuar_bedenler_aksesuar_beden_id_fkey FOREIGN KEY (aksesuar_beden_id) REFERENCES public.aksesuar_bedenler(id)
);
CREATE TABLE public.model_beden_dagilimi (
  id integer NOT NULL DEFAULT nextval('model_beden_dagilimi_id_seq'::regclass),
  model_id uuid NOT NULL,
  beden_kodu character varying NOT NULL,
  siparis_adedi integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT model_beden_dagilimi_pkey PRIMARY KEY (id),
  CONSTRAINT model_beden_dagilimi_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT model_beden_dagilimi_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.model_karlilik_ozetleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  model_id uuid NOT NULL UNIQUE,
  aktif_plan_id uuid,
  siparis_adedi integer NOT NULL DEFAULT 0,
  tamamlanan_adet integer NOT NULL DEFAULT 0,
  fire_adedi integer NOT NULL DEFAULT 0,
  plan_birim_maliyet numeric NOT NULL DEFAULT 0,
  gercek_birim_maliyet numeric NOT NULL DEFAULT 0,
  plan_toplam_maliyet numeric NOT NULL DEFAULT 0,
  gercek_toplam_maliyet numeric NOT NULL DEFAULT 0,
  satis_birim_fiyati numeric NOT NULL DEFAULT 0,
  satis_geliri numeric NOT NULL DEFAULT 0,
  brut_kar numeric NOT NULL DEFAULT 0,
  brut_kar_marji numeric NOT NULL DEFAULT 0,
  maliyet_sapmasi numeric NOT NULL DEFAULT 0,
  maliyet_sapma_orani numeric NOT NULL DEFAULT 0,
  fire_orani numeric NOT NULL DEFAULT 0,
  durum text NOT NULL DEFAULT 'fiyat_eksik'::text CHECK (durum = ANY (ARRAY['hedefte'::text, 'hedef_alti'::text, 'zarar_riski'::text, 'fiyat_eksik'::text])),
  hesaplama_tarihi timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT model_karlilik_ozetleri_pkey PRIMARY KEY (id),
  CONSTRAINT model_karlilik_ozetleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT model_karlilik_ozetleri_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT model_karlilik_ozetleri_aktif_plan_id_fkey FOREIGN KEY (aktif_plan_id) REFERENCES public.model_maliyet_planlari(id)
);
CREATE TABLE public.model_kritikleri (
  id integer NOT NULL DEFAULT nextval('model_kritikleri_id_seq'::regclass),
  model_id uuid NOT NULL,
  kritik_baslik character varying NOT NULL,
  kritik_aciklama text,
  kritik_turu character varying DEFAULT 'genel'::character varying,
  oncelik character varying DEFAULT 'orta'::character varying,
  durum character varying DEFAULT 'aktif'::character varying,
  olusturan_kullanici_id uuid,
  olusturma_tarihi timestamp with time zone DEFAULT now(),
  guncelleme_tarihi timestamp with time zone DEFAULT now(),
  cozum_tarihi timestamp with time zone,
  cozum_aciklamasi text,
  firma_id uuid NOT NULL,
  CONSTRAINT model_kritikleri_pkey PRIMARY KEY (id),
  CONSTRAINT model_kritikleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT model_kritikleri_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT model_kritikleri_olusturan_kullanici_id_fkey FOREIGN KEY (olusturan_kullanici_id) REFERENCES auth.users(id)
);
CREATE TABLE public.model_maliyet_gerceklesen (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  model_id uuid NOT NULL,
  plan_id uuid,
  kalem_tipi text NOT NULL,
  kaynak text NOT NULL DEFAULT 'manuel'::text CHECK (kaynak = ANY (ARRAY['manuel'::text, 'stok'::text, 'fatura'::text, 'uretim'::text, 'sevkiyat'::text])),
  belge_turu text,
  belge_id text,
  miktar numeric NOT NULL DEFAULT 0,
  birim text NOT NULL DEFAULT 'adet'::text,
  birim_fiyat numeric NOT NULL DEFAULT 0,
  toplam_tutar numeric NOT NULL DEFAULT 0,
  fire_adedi integer NOT NULL DEFAULT 0,
  tarih date NOT NULL DEFAULT CURRENT_DATE,
  aciklama text,
  created_by uuid DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT model_maliyet_gerceklesen_pkey PRIMARY KEY (id),
  CONSTRAINT model_maliyet_gerceklesen_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT model_maliyet_gerceklesen_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT model_maliyet_gerceklesen_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.model_maliyet_planlari(id)
);
CREATE TABLE public.model_maliyet_kalemleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  model_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  kalem_tipi text NOT NULL CHECK (kalem_tipi = ANY (ARRAY['iplik'::text, 'orgu'::text, 'dikim'::text, 'utu'::text, 'yikama'::text, 'ilik_dugme'::text, 'fermuar'::text, 'baski_nakis'::text, 'aksesuar'::text, 'genel_aksesuar'::text, 'genel_gider'::text, 'paketleme'::text, 'diger'::text])),
  aciklama text,
  miktar numeric NOT NULL DEFAULT 1,
  birim text NOT NULL DEFAULT 'adet'::text,
  birim_fiyat numeric NOT NULL DEFAULT 0,
  plan_birim_maliyet numeric NOT NULL DEFAULT 0,
  plan_toplam_tutar numeric NOT NULL DEFAULT 0,
  kaynak text NOT NULL DEFAULT 'manuel'::text CHECK (kaynak = ANY (ARRAY['manuel'::text, 'model'::text, 'stok'::text, 'fatura'::text, 'uretim'::text])),
  sira_no integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT model_maliyet_kalemleri_pkey PRIMARY KEY (id),
  CONSTRAINT model_maliyet_kalemleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT model_maliyet_kalemleri_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT model_maliyet_kalemleri_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.model_maliyet_planlari(id)
);
CREATE TABLE public.model_maliyet_planlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  model_id uuid NOT NULL,
  versiyon_no integer NOT NULL DEFAULT 1,
  durum text NOT NULL DEFAULT 'aktif'::text CHECK (durum = ANY (ARRAY['taslak'::text, 'aktif'::text, 'arsiv'::text])),
  plan_tipi text NOT NULL DEFAULT 'plan'::text CHECK (plan_tipi = ANY (ARRAY['hedef'::text, 'plan'::text, 'revize'::text])),
  para_birimi text NOT NULL DEFAULT 'TRY'::text,
  kur numeric NOT NULL DEFAULT 1,
  hedef_kar_marji numeric NOT NULL DEFAULT 0,
  hedef_satis_fiyati numeric NOT NULL DEFAULT 0,
  plan_adet integer NOT NULL DEFAULT 0,
  plan_fire_orani numeric NOT NULL DEFAULT 0,
  plan_birim_maliyet numeric NOT NULL DEFAULT 0,
  plan_toplam_maliyet numeric NOT NULL DEFAULT 0,
  plan_satis_fiyati numeric NOT NULL DEFAULT 0,
  notlar text,
  created_by uuid DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT model_maliyet_planlari_pkey PRIMARY KEY (id),
  CONSTRAINT model_maliyet_planlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT model_maliyet_planlari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.model_workflow_gecmisi (
  id integer NOT NULL DEFAULT nextval('model_workflow_gecmisi_id_seq'::regclass),
  model_id uuid NOT NULL,
  sevk_talebi_id integer,
  onceki_durum character varying,
  yeni_durum character varying NOT NULL,
  onceki_atolye_id integer,
  yeni_atolye_id integer,
  islem_yapan_user_id uuid NOT NULL,
  islem_tarihi timestamp with time zone DEFAULT now(),
  aciklama text,
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT model_workflow_gecmisi_pkey PRIMARY KEY (id),
  CONSTRAINT model_workflow_gecmisi_onceki_atolye_id_fkey FOREIGN KEY (onceki_atolye_id) REFERENCES public.atolyeler(id),
  CONSTRAINT model_workflow_gecmisi_sevk_talebi_id_fkey FOREIGN KEY (sevk_talebi_id) REFERENCES public.sevk_talepleri(id),
  CONSTRAINT model_workflow_gecmisi_yeni_atolye_id_fkey FOREIGN KEY (yeni_atolye_id) REFERENCES public.atolyeler(id)
);
CREATE TABLE public.modeller (
  id integer NOT NULL DEFAULT nextval('modeller_id_seq'::regclass),
  model_adi character varying NOT NULL,
  model_kodu character varying UNIQUE,
  aciklama text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  konfeksiyon_durumu text DEFAULT 'bekliyor'::text CHECK (konfeksiyon_durumu = ANY (ARRAY['bekliyor'::text, 'atandi'::text, 'onaylandi'::text, 'uretimde'::text, 'tamamlandi'::text])),
  yikama_durumu text DEFAULT 'bekliyor'::text CHECK (yikama_durumu = ANY (ARRAY['bekliyor'::text, 'atandi'::text, 'onaylandi'::text, 'uretimde'::text, 'tamamlandi'::text])),
  utu_durumu text DEFAULT 'bekliyor'::text CHECK (utu_durumu = ANY (ARRAY['bekliyor'::text, 'atandi'::text, 'onaylandi'::text, 'uretimde'::text, 'tamamlandi'::text])),
  ilik_dugme_durumu text DEFAULT 'bekliyor'::text CHECK (ilik_dugme_durumu = ANY (ARRAY['bekliyor'::text, 'atandi'::text, 'onaylandi'::text, 'uretimde'::text, 'tamamlandi'::text])),
  kalite_kontrol_durumu text DEFAULT 'bekliyor'::text CHECK (kalite_kontrol_durumu = ANY (ARRAY['bekliyor'::text, 'atandi'::text, 'onaylandi'::text, 'uretimde'::text, 'tamamlandi'::text])),
  paketleme_durumu text DEFAULT 'bekliyor'::text CHECK (paketleme_durumu = ANY (ARRAY['bekliyor'::text, 'atandi'::text, 'onaylandi'::text, 'uretimde'::text, 'tamamlandi'::text])),
  dokuma_durumu text DEFAULT 'beklemede'::text,
  firma_id uuid NOT NULL,
  CONSTRAINT modeller_pkey PRIMARY KEY (id),
  CONSTRAINT modeller_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.modul_tanimlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  modul_kodu character varying NOT NULL UNIQUE,
  modul_adi character varying NOT NULL,
  aciklama text,
  kategori character varying NOT NULL,
  ikon character varying,
  sira_no integer DEFAULT 0,
  bagimliliklar jsonb DEFAULT '[]'::jsonb,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modul_tanimlari_pkey PRIMARY KEY (id)
);
CREATE TABLE public.musteriler (
  id integer NOT NULL DEFAULT nextval('musteriler_id_seq'::regclass),
  ad character varying NOT NULL,
  soyad character varying NOT NULL,
  sirket_adi character varying,
  telefon character varying,
  email character varying,
  adres text,
  vergi_no character varying,
  tc_kimlik_no character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  kayit_tarihi date,
  firma_id uuid NOT NULL,
  CONSTRAINT musteriler_pkey PRIMARY KEY (id),
  CONSTRAINT musteriler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.nakis_atamalari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  atanan_firma_id uuid,
  adet integer DEFAULT 0,
  talep_edilen_adet integer DEFAULT 0,
  tamamlanan_adet integer DEFAULT 0,
  durum text DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  aciklama text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  kabul_tarihi timestamp with time zone,
  teslim_tarihi timestamp with time zone,
  son_guncelleme_tarihi timestamp with time zone,
  tedarikci_id integer,
  uretici_notlari text,
  tamamlama_tarihi timestamp with time zone,
  kabul_edilen_adet integer,
  onay_tarihi timestamp with time zone,
  firma_id uuid NOT NULL,
  CONSTRAINT nakis_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT nakis_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT nakis_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT fk_nakis_atamalari_tedarikci FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id)
);
CREATE TABLE public.odeme_kayitlari (
  id integer NOT NULL DEFAULT nextval('odeme_kayitlari_id_seq'::regclass),
  odeme_turu character varying NOT NULL,
  referans_id integer,
  tutar numeric NOT NULL,
  odeme_yontemi character varying,
  odeme_tarihi date NOT NULL,
  aciklama text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  tur character varying,
  durum character varying DEFAULT 'beklemede'::character varying,
  onaylayan_user_id uuid,
  onay_tarihi timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  tarih date,
  user_id uuid,
  firma_id uuid NOT NULL,
  CONSTRAINT odeme_kayitlari_pkey PRIMARY KEY (id),
  CONSTRAINT odeme_kayitlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.odemeler (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personel_id uuid,
  odeme_turu character varying CHECK (odeme_turu::text = ANY (ARRAY['avans'::character varying::text, 'maas'::character varying::text, 'prim'::character varying::text, 'ikramiye'::character varying::text, 'diger'::character varying::text])),
  tutar numeric CHECK (tutar > 0::numeric),
  aciklama text,
  odeme_tarihi date,
  odeme_yontemi character varying DEFAULT 'nakit'::character varying CHECK (odeme_yontemi::text = ANY (ARRAY['nakit'::character varying::text, 'banka'::character varying::text, 'cek'::character varying::text])),
  durum character varying DEFAULT 'beklemede'::character varying CHECK (durum::text = ANY (ARRAY['beklemede'::character varying::text, 'onaylandi'::character varying::text, 'odendi'::character varying::text, 'iptal'::character varying::text])),
  onaylayan_user_id uuid,
  onay_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  CONSTRAINT odemeler_pkey PRIMARY KEY (id),
  CONSTRAINT odemeler_onaylayan_user_id_fkey FOREIGN KEY (onaylayan_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ozel_personel (
  id integer NOT NULL DEFAULT nextval('ozel_personel_id_seq'::regclass),
  user_id uuid,
  personel_turu text NOT NULL CHECK (personel_turu = ANY (ARRAY['kalite_guvence'::text, 'sevkiyat_personeli'::text, 'muhasebe'::text, 'satis'::text, 'tasarim'::text, 'planlama'::text, 'depo'::text])),
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ozel_personel_pkey PRIMARY KEY (id),
  CONSTRAINT ozel_personel_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.paketleme_atamalari (
  id integer NOT NULL DEFAULT nextval('paketleme_atamalari_id_seq'::regclass),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  durum text NOT NULL DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  atama_tarihi timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  paketleme_baslangic_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  paket_tipi text,
  paket_adedi integer,
  notlar text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  planlanan_bitis_tarihi timestamp with time zone,
  adet integer,
  talep_edilen_adet integer,
  tamamlanan_adet integer DEFAULT 0,
  hedef_asama text,
  tamamlanma_tarihi timestamp with time zone,
  sevk_tarihi timestamp with time zone,
  sevk_adresi text,
  kargo_firmasi character varying,
  takip_no character varying,
  fire_adet integer DEFAULT 0,
  baslama_tarihi timestamp with time zone,
  firma_id uuid NOT NULL,
  CONSTRAINT paketleme_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT paketleme_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT paketleme_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT paketleme_atamalari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.personel (
  id integer NOT NULL DEFAULT nextval('personel_id_seq'::regclass),
  ad character varying NOT NULL,
  soyad character varying NOT NULL,
  tc_kimlik_no character varying UNIQUE,
  telefon character varying,
  email character varying CHECK (email IS NULL OR email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  adres text,
  maas numeric DEFAULT 0,
  baslama_tarihi date,
  durum character varying DEFAULT 'aktif'::character varying CHECK (durum::text = ANY (ARRAY['aktif'::character varying::text, 'pasif'::character varying::text, 'izinli'::character varying::text, 'isten_ayrilmis'::character varying::text])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  user_id uuid UNIQUE,
  tckn character varying UNIQUE CHECK (tckn IS NULL OR validate_tckn(tckn::text)),
  pozisyon character varying,
  departman character varying,
  ise_baslangic date,
  brut_maas numeric CHECK (brut_maas IS NULL OR brut_maas >= 0::numeric),
  sgk_sicil_no character varying,
  gunluk_calisma_saati numeric DEFAULT 8.0 CHECK (gunluk_calisma_saati IS NULL OR gunluk_calisma_saati > 0::numeric),
  haftalik_calisma_gunu integer DEFAULT 5,
  yol_ucreti numeric DEFAULT 0.0,
  yemek_ucreti numeric DEFAULT 0.0,
  ekstra_prim numeric DEFAULT 0.0,
  elden_maas numeric DEFAULT 0.0,
  banka_maas numeric DEFAULT 0.0,
  net_maas numeric CHECK (net_maas IS NULL OR net_maas >= 0::numeric),
  yillik_izin_hakki integer DEFAULT 14,
  firma_id uuid NOT NULL,
  isten_cikis_tarihi date,
  isten_cikis_nedeni text,
  silme_tarihi timestamp with time zone,
  CONSTRAINT personel_pkey PRIMARY KEY (id),
  CONSTRAINT personel_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT personel_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.personel_arsiv (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personel_id uuid,
  belge_turu character varying CHECK (belge_turu::text = ANY (ARRAY['cv'::character varying::text, 'diploma'::character varying::text, 'sertifika'::character varying::text, 'saglik_raporu'::character varying::text, 'kimlik'::character varying::text, 'ikametgah'::character varying::text, 'diger'::character varying::text])),
  belge_adi character varying,
  dosya_yolu text,
  dosya_boyutu bigint,
  mime_type character varying,
  aciklama text,
  yukleme_tarihi timestamp with time zone DEFAULT now(),
  yukleyen_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  onaylayan_id uuid,
  CONSTRAINT personel_arsiv_pkey PRIMARY KEY (id),
  CONSTRAINT personel_arsiv_yukleyen_user_id_fkey FOREIGN KEY (yukleyen_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.personel_donem (
  id integer NOT NULL DEFAULT nextval('personel_donem_id_seq'::regclass),
  donem_id integer,
  personel_id uuid NOT NULL,
  toplam_mesai_saati numeric DEFAULT 0,
  toplam_izin_gunu integer DEFAULT 0,
  toplam_avans numeric DEFAULT 0,
  kalan_yillik_izin integer DEFAULT 0,
  bordro_durumu character varying DEFAULT 'beklemede'::character varying CHECK (bordro_durumu::text = ANY (ARRAY['beklemede'::character varying::text, 'hazirlandi'::character varying::text, 'odendi'::character varying::text])),
  olusturulma_tarihi timestamp without time zone DEFAULT now(),
  guncellenme_tarihi timestamp without time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT personel_donem_pkey PRIMARY KEY (id),
  CONSTRAINT personel_donem_donem_id_fkey FOREIGN KEY (donem_id) REFERENCES public.donemler(id),
  CONSTRAINT personel_donem_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.puantaj (
  id integer NOT NULL DEFAULT nextval('puantaj_id_seq'::regclass),
  personel_id uuid,
  tarih date NOT NULL,
  giris_saati time without time zone,
  cikis_saati time without time zone,
  toplam_saat numeric DEFAULT 0,
  mesai_saati numeric DEFAULT 0,
  aciklama text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  donem integer,
  yil integer,
  calisan_gun_sayisi integer DEFAULT 0,
  izin_gun_sayisi integer DEFAULT 0,
  fazla_mesai_saati numeric DEFAULT 0,
  toplam_maas numeric DEFAULT 0,
  kesintiler numeric DEFAULT 0,
  net_odeme numeric DEFAULT 0,
  onaylandi boolean DEFAULT false,
  onaylayan_user_id uuid,
  onay_tarihi timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  ad character varying,
  ay integer,
  gun integer DEFAULT 0,
  calisma_saati integer DEFAULT 0,
  fazla_mesai integer DEFAULT 0,
  eksik_gun integer DEFAULT 0,
  devamsizlik integer DEFAULT 0,
  firma_id uuid NOT NULL,
  CONSTRAINT puantaj_pkey PRIMARY KEY (id),
  CONSTRAINT puantaj_onaylayan_user_id_fkey FOREIGN KEY (onaylayan_user_id) REFERENCES auth.users(id),
  CONSTRAINT puantaj_personel_id_fkey FOREIGN KEY (personel_id) REFERENCES public.personel(user_id),
  CONSTRAINT puantaj_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.rol_sayfa_yetkileri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid NOT NULL,
  rol text NOT NULL,
  sayfa_kodu text NOT NULL,
  aktif boolean DEFAULT true,
  olusturulma_zamani timestamp with time zone DEFAULT now(),
  guncelleme_zamani timestamp with time zone DEFAULT now(),
  CONSTRAINT rol_sayfa_yetkileri_pkey PRIMARY KEY (id),
  CONSTRAINT rol_sayfa_yetkileri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.sevk_irsaliye_kalemleri (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  irsaliye_id bigint NOT NULL,
  firma_id text NOT NULL,
  model_id text,
  beden_kodu text,
  koli_adedi integer,
  adet integer NOT NULL CHECK (adet > 0),
  birim text NOT NULL DEFAULT 'adet'::text,
  aciklama text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sevk_irsaliye_kalemleri_pkey PRIMARY KEY (id),
  CONSTRAINT sevk_irsaliye_kalemleri_irsaliye_id_fkey FOREIGN KEY (irsaliye_id) REFERENCES public.sevk_irsaliyeleri(id)
);
CREATE TABLE public.sevk_irsaliyeleri (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  firma_id text NOT NULL,
  irsaliye_no text NOT NULL,
  kaynak_asama text NOT NULL,
  hedef_asama text NOT NULL,
  kaynak_tablo text,
  kaynak_kayit_id text,
  model_id text NOT NULL,
  sevk_adedi integer NOT NULL CHECK (sevk_adedi > 0),
  hedef_tedarikci_id bigint,
  sevk_tarihi timestamp with time zone NOT NULL DEFAULT now(),
  durum text NOT NULL DEFAULT 'onaylandi'::text,
  notlar text,
  idempotency_key text,
  created_by text,
  onaylayan_id text,
  onay_tarihi timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sevk_irsaliyeleri_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sevk_talepleri (
  id integer NOT NULL DEFAULT nextval('sevk_talepleri_id_seq'::regclass),
  model_id uuid NOT NULL,
  kaynak_atolye_id integer NOT NULL,
  hedef_atolye_id integer NOT NULL,
  talep_eden_user_id uuid NOT NULL,
  sevk_adeti integer NOT NULL DEFAULT 0,
  durum character varying DEFAULT 'bekliyor'::character varying CHECK (durum::text = ANY (ARRAY['bekliyor'::text, 'kalite_onaylandi'::text, 'alindi'::text, 'yolda'::text, 'teslimde'::text, 'teslim_edildi'::text, 'iptal'::text])),
  onceligi character varying DEFAULT 'normal'::character varying,
  kalite_kontrol_user_id uuid,
  kalite_kontrol_tarihi timestamp with time zone,
  kalite_notlari text,
  kalite_onay_durumu boolean,
  sofor_user_id uuid,
  alinan_tarih timestamp with time zone,
  sevkiyat_baslama_tarihi timestamp with time zone,
  tahmini_teslim_tarihi timestamp with time zone,
  gercek_teslim_tarihi timestamp with time zone,
  teslim_alan_user_id uuid,
  teslim_notlari text,
  hasar_raporu text,
  teslim_onay_durumu boolean,
  aciklama text,
  oncelik_nedeni text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  CONSTRAINT sevk_talepleri_pkey PRIMARY KEY (id),
  CONSTRAINT sevk_talepleri_hedef_atolye_id_fkey FOREIGN KEY (hedef_atolye_id) REFERENCES public.atolyeler(id),
  CONSTRAINT sevk_talepleri_kaynak_atolye_id_fkey FOREIGN KEY (kaynak_atolye_id) REFERENCES public.atolyeler(id),
  CONSTRAINT sevk_talepleri_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.sevkiyat_kayitlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  uretim_kaydi_id uuid,
  sevkiyat_personeli_id uuid,
  alinan_adet integer NOT NULL CHECK (alinan_adet > 0),
  hedef_atolye_id integer,
  sevkiyat_tarihi timestamp with time zone NOT NULL DEFAULT now(),
  notlar text,
  created_at timestamp with time zone DEFAULT now(),
  firma_id uuid NOT NULL,
  kaynak_atama_tablosu text,
  kaynak_atama_id bigint,
  idempotency_key text,
  model_id text,
  kalite_kontrol_id text,
  onceki_asama text,
  hedef_asama text,
  sevk_edilen_adet integer DEFAULT 0,
  kalan_adet integer DEFAULT 0,
  durum text DEFAULT 'beklemede'::text,
  alis_tarihi timestamp with time zone DEFAULT now(),
  sevk_tarihi timestamp with time zone,
  tamamlanma_tarihi timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  beden_detaylari jsonb,
  hedef_tedarikci_id bigint,
  CONSTRAINT sevkiyat_kayitlari_pkey PRIMARY KEY (id),
  CONSTRAINT sevkiyat_kayitlari_hedef_atolye_id_fkey FOREIGN KEY (hedef_atolye_id) REFERENCES public.atolyeler(id),
  CONSTRAINT sevkiyat_kayitlari_sevkiyat_personeli_id_fkey FOREIGN KEY (sevkiyat_personeli_id) REFERENCES auth.users(id),
  CONSTRAINT sevkiyat_kayitlari_uretim_kaydi_id_fkey FOREIGN KEY (uretim_kaydi_id) REFERENCES public.uretim_kayitlari(id),
  CONSTRAINT sevkiyat_kayitlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.sirket_bilgileri (
  id integer NOT NULL DEFAULT nextval('sirket_bilgileri_id_seq'::regclass),
  sirket_adi character varying NOT NULL,
  vergi_no character varying NOT NULL UNIQUE,
  vergi_dairesi character varying,
  adres text,
  telefon character varying,
  email character varying,
  web_sitesi character varying,
  logo_url character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sirket_bilgileri_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sistem_ayarlari (
  id integer NOT NULL DEFAULT nextval('sistem_ayarlari_id_seq'::regclass),
  anahtar character varying NOT NULL UNIQUE,
  deger text,
  aciklama text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sistem_ayarlari_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tedarikci_model_kapasiteleri (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  firma_id text NOT NULL,
  tedarikci_id text NOT NULL,
  model_id text NOT NULL,
  gunluk_kapasite numeric NOT NULL CHECK (gunluk_kapasite > 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tedarikci_model_kapasiteleri_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tedarikciler (
  id integer NOT NULL DEFAULT nextval('tedarikciler_id_seq'::regclass),
  ad character varying NOT NULL,
  soyad character varying NOT NULL,
  sirket character varying NOT NULL,
  telefon character varying NOT NULL,
  email character varying NOT NULL,
  tedarikci_tipi character varying NOT NULL,
  faaliyet character varying NOT NULL,
  durum character varying NOT NULL,
  vergi_no character varying,
  tc_kimlik_no character varying,
  iban_no character varying,
  banka_hesap_no character varying,
  iban character varying,
  banka_adi character varying,
  sube_kodu character varying,
  sube_adi character varying,
  banka_subesi character varying,
  cep_telefonu character varying,
  web_sitesi character varying,
  yetkili_kisi character varying,
  iskonto_orani numeric DEFAULT 0,
  mevcut_borc numeric DEFAULT 0,
  hesap_sahibi character varying,
  notlar text,
  kayit_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  varsayilan_iskonto numeric DEFAULT 0,
  toplam_borc numeric DEFAULT 0,
  son_odeme_tarihi date,
  faks character varying,
  adres text,
  aktif boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  guncelleme_tarihi date,
  tedarikci_turu text,
  faaliyet_alani text,
  firma_id uuid NOT NULL,
  gunluk_uretim_kapasitesi numeric,
  CONSTRAINT tedarikciler_pkey PRIMARY KEY (id),
  CONSTRAINT tedarikciler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.teknik_dosyalar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  dosya_adi text NOT NULL,
  dosya_tipi text,
  dosya_url text,
  dosya_boyutu integer,
  aciklama text,
  firma_id uuid NOT NULL,
  CONSTRAINT teknik_dosyalar_pkey PRIMARY KEY (id),
  CONSTRAINT teknik_dosyalar_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT teknik_dosyalar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.triko_takip (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  marka text NOT NULL,
  item_no text NOT NULL UNIQUE,
  model_adi text,
  sezon text,
  koleksiyon text,
  urun_kategorisi text,
  triko_tipi text,
  cinsiyet text,
  yas_grubu text,
  yaka_tipi text,
  kol_tipi text,
  ana_iplik_turu text,
  iplik_karisimi text,
  iplik_kalinligi text,
  iplik_markasi text,
  iplik_renk_kodu text,
  iplik_numarasi text,
  ana_renkler ARRAY,
  desen_tipi text,
  desen_detayi text,
  renk_kombinasyonu text,
  bedenler jsonb,
  toplam_adet integer,
  gramaj text,
  orgu_firmasi text,
  iplik_tedarikci text,
  boyahane text,
  ilik_dugme_metal_aksesuar text,
  konfeksiyon_firmasi text,
  utu_pres_firmasi text,
  yikama_firmasi text,
  makine_tipi text,
  igne_no text,
  gauge text,
  orgu_sikligi text,
  teknik_gramaj text,
  siparis_tarihi date,
  termin_tarihi date,
  durum text DEFAULT 'Beklemede'::text,
  tamamlandi boolean DEFAULT false,
  yuklenen_adet integer DEFAULT 0,
  iplik_geldi boolean DEFAULT false,
  iplik_gelis_tarihi date,
  orguye_baslayabilir boolean DEFAULT false,
  kase_onayi boolean DEFAULT false,
  yukleme_tarihi date,
  orgu_firma jsonb DEFAULT '[]'::jsonb,
  konfeksiyon_firma jsonb DEFAULT '[]'::jsonb,
  utu_firma jsonb DEFAULT '[]'::jsonb,
  ozel_talimatlar text,
  genel_notlar text,
  renk text,
  urun_cinsi text,
  iplik_cinsi text,
  uretici text,
  adet integer,
  toplam_maliyet numeric,
  kur text DEFAULT 'TRY'::text,
  siparis_notu text,
  first_fit_gonderildi text CHECK (first_fit_gonderildi = ANY (ARRAY['evet'::text, 'hayir'::text])),
  first_fit_aciklama text,
  size_set_gonderildi text CHECK (size_set_gonderildi = ANY (ARRAY['evet'::text, 'hayir'::text])),
  size_set_aciklama text,
  pps_numunesi_gonderildi text CHECK (pps_numunesi_gonderildi = ANY (ARRAY['evet'::text, 'hayir'::text])),
  pps_numunesi_aciklama text,
  iplik_kg_fiyati numeric,
  iplik_maliyeti numeric,
  makina_cikis_suresi numeric,
  makina_dk_fiyati numeric,
  orgu_fiyat numeric,
  dikim_fiyat numeric,
  utu_fiyat numeric,
  yikama_fiyat numeric,
  ilik_dugme_fiyat numeric,
  fermuar_fiyat numeric,
  aksesuar_fiyat numeric,
  genel_aksesuar_fiyat numeric,
  genel_gider_fiyat numeric,
  kar_marji numeric,
  pesin_fiyat numeric,
  vade_ay integer DEFAULT 0,
  vade_orani numeric,
  firma_id uuid NOT NULL,
  uretim_dali text DEFAULT 'triko'::text,
  CONSTRAINT triko_takip_pkey PRIMARY KEY (id),
  CONSTRAINT triko_takip_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.uretim_kayitlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid NOT NULL,
  asama text NOT NULL CHECK (asama = ANY (ARRAY['orgu'::text, 'konfeksiyon'::text, 'yikama'::text, 'nakis'::text, 'ilik_dugme'::text, 'utu'::text, 'diger'::text])),
  firma_id integer,
  tamamlanan_adet integer NOT NULL CHECK (tamamlanan_adet > 0),
  tamamlanma_tarihi timestamp with time zone,
  uretici_user_id uuid,
  durum text NOT NULL DEFAULT 'kalite_bekliyor'::text CHECK (durum = ANY (ARRAY['firma_onay_bekliyor'::text, 'uretim_baslamadi'::text, 'uretimde'::text, 'uretim_tamamlandi'::text, 'kalite_bekliyor'::text, 'kalite_onaylandi'::text, 'kalite_reddedildi'::text, 'sevkiyat_bekliyor'::text, 'sevk_edildi'::text, 'tamamlandi'::text, 'beklemede'::text, 'devam_ediyor'::text, 'tamamlandi_old'::text])),
  kalite_onay_durumu boolean,
  kalite_kontrol_user_id uuid,
  kalite_kontrol_tarihi timestamp with time zone,
  kalite_notlari text,
  sevkiyat_tarihi timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  baslangic_tarihi timestamp with time zone,
  bitis_tarihi timestamp with time zone,
  firma_onay_tarihi timestamp with time zone,
  firma_onay_user_id uuid,
  baslama_tarihi timestamp with time zone,
  firma_onay_durumu boolean,
  notlar text,
  atama_durumu text DEFAULT 'beklemede'::text CHECK (atama_durumu = ANY (ARRAY['beklemede'::text, 'firma_onay_bekliyor'::text, 'onaylandi'::text, 'reddedildi'::text, 'uretimde'::text, 'tamamlandi'::text])),
  firma_red_nedeni text,
  uretim_baslangic_tarihi timestamp with time zone,
  uretilen_adet integer DEFAULT 0 CHECK (uretilen_adet >= 0),
  atama_yapan_user_id uuid,
  CONSTRAINT uretim_kayitlari_pkey PRIMARY KEY (id),
  CONSTRAINT uretim_kayitlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.atolyeler(id),
  CONSTRAINT uretim_kayitlari_firma_onay_user_id_fkey FOREIGN KEY (firma_onay_user_id) REFERENCES auth.users(id),
  CONSTRAINT uretim_kayitlari_kalite_kontrol_user_id_fkey FOREIGN KEY (kalite_kontrol_user_id) REFERENCES auth.users(id),
  CONSTRAINT uretim_kayitlari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id),
  CONSTRAINT uretim_kayitlari_uretici_user_id_fkey FOREIGN KEY (uretici_user_id) REFERENCES auth.users(id),
  CONSTRAINT uretim_kayitlari_atama_yapan_user_id_fkey FOREIGN KEY (atama_yapan_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.uretim_modulleri (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  modul_kodu character varying NOT NULL UNIQUE,
  modul_adi character varying NOT NULL,
  tekstil_dali character varying NOT NULL,
  aciklama text,
  uretim_asamalari jsonb NOT NULL DEFAULT '[]'::jsonb,
  varsayilan_asamalar jsonb NOT NULL DEFAULT '[]'::jsonb,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  sira_no integer NOT NULL,
  CONSTRAINT uretim_modulleri_pkey PRIMARY KEY (id)
);
CREATE TABLE public.uretim_plani (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  planlanan_baslangic date,
  planlanan_bitis date,
  gercek_baslangic date,
  gercek_bitis date,
  iplik_tedarik_durumu text DEFAULT 'Beklemede'::text,
  iplik_tedarik_tarih date,
  orgu_durumu text DEFAULT 'Beklemede'::text,
  orgu_tarih date,
  boyama_durumu text DEFAULT 'Beklemede'::text,
  boyama_tarih date,
  konfeksiyon_durumu text DEFAULT 'Beklemede'::text,
  konfeksiyon_tarih date,
  finishing_durumu text DEFAULT 'Beklemede'::text,
  finishing_tarih date,
  tamamlanan_miktar integer DEFAULT 0,
  toplam_miktar integer,
  tamamlanma_yuzdesi numeric DEFAULT 0,
  uretim_notu text,
  CONSTRAINT uretim_plani_pkey PRIMARY KEY (id),
  CONSTRAINT uretim_plani_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.urun_depo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id uuid NOT NULL,
  kalite_tipi character varying NOT NULL CHECK (kalite_tipi::text = ANY (ARRAY['1. Kalite'::character varying, '2. & 3. Kalite'::character varying]::text[])),
  adet integer NOT NULL CHECK (adet > 0),
  aciklama text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  satildi boolean DEFAULT false,
  satilan_adet integer DEFAULT 0,
  satilan_tutar numeric DEFAULT 0,
  satis_tarihi timestamp with time zone,
  marka character varying,
  renk character varying,
  firma_id uuid NOT NULL,
  CONSTRAINT urun_depo_pkey PRIMARY KEY (id),
  CONSTRAINT urun_depo_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT fk_model FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.user_roles (
  id integer NOT NULL DEFAULT nextval('user_roles_id_seq'::regclass),
  user_id uuid,
  role character varying NOT NULL DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'firma_sahibi'::character varying, 'firma_admin'::character varying, 'yonetici'::character varying, 'kullanici'::character varying, 'personel'::character varying, 'dokumaci'::character varying, 'konfeksiyoncu'::character varying, 'kalite_kontrol'::character varying, 'sevkiyat'::character varying, 'sofor'::character varying, 'muhasebeci'::character varying, 'depocu'::character varying, 'nakis'::character varying, 'yikama'::character varying, 'utu_paket'::character varying, 'ilik_dugme'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  atolye_id integer,
  yetki_seviyesi integer DEFAULT 1,
  aktif boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  firma_id uuid,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_atolye_id_fkey FOREIGN KEY (atolye_id) REFERENCES public.atolyeler(id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.utu_atamalari (
  id integer NOT NULL DEFAULT nextval('utu_atamalari_id_seq'::regclass),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  durum text NOT NULL DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  atama_tarihi timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  uretim_baslangic_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  utu_tipi text,
  notlar text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  tedarikci_id integer,
  adet integer,
  talep_edilen_adet integer,
  tamamlanan_adet integer,
  uretici_notlari text,
  kabul_edilen_adet integer,
  planlanan_bitis_tarihi timestamp with time zone,
  fire_adet integer DEFAULT 0,
  baslama_tarihi timestamp with time zone,
  hedef_adet integer DEFAULT 0,
  fire_dusulmus_adet integer DEFAULT 0,
  firma_id uuid NOT NULL,
  CONSTRAINT utu_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT utu_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT utu_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT fk_utu_atamalari_tedarikci FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT utu_atamalari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.utu_beden_takip (
  id integer NOT NULL DEFAULT nextval('utu_beden_takip_id_seq'::regclass),
  atama_id integer NOT NULL,
  model_id uuid NOT NULL,
  beden_kodu character varying NOT NULL,
  hedef_adet integer NOT NULL DEFAULT 0,
  uretilen_adet integer DEFAULT 0,
  kabul_edilen_adet integer DEFAULT 0,
  fire_adet integer DEFAULT 0,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  guncelleme_tarihi timestamp with time zone DEFAULT now(),
  CONSTRAINT utu_beden_takip_pkey PRIMARY KEY (id),
  CONSTRAINT utu_beden_takip_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.workflow_transition_log (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  firma_id text NOT NULL,
  table_name text NOT NULL,
  record_id bigint NOT NULL,
  from_status text,
  to_status text NOT NULL,
  idempotency_key text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workflow_transition_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.yetki_tanimlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firma_id uuid,
  rol character varying NOT NULL,
  modul_kodu character varying NOT NULL,
  yetki character varying NOT NULL,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT yetki_tanimlari_pkey PRIMARY KEY (id),
  CONSTRAINT yetki_tanimlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);
CREATE TABLE public.yikama_atamalari (
  id integer NOT NULL DEFAULT nextval('yikama_atamalari_id_seq'::regclass),
  model_id uuid NOT NULL,
  atanan_kullanici_id uuid,
  durum text NOT NULL DEFAULT 'atandi'::text CHECK (durum = ANY (ARRAY['bekleyen'::text, 'atandi'::text, 'onaylandi'::text, 'baslandi'::text, 'devam_ediyor'::text, 'uretimde'::text, 'baslatildi'::text, 'kismi_tamamlandi'::text, 'tamamlandi'::text, 'sevk_ediliyor'::text, 'reddedildi'::text, 'iptal'::text])),
  atama_tarihi timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  onay_tarihi timestamp with time zone,
  red_sebebi text,
  uretim_baslangic_tarihi timestamp with time zone,
  tamamlama_tarihi timestamp with time zone,
  yikama_turu text,
  notlar text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  tedarikci_id integer,
  adet integer,
  talep_edilen_adet integer,
  tamamlanan_adet integer,
  uretici_notlari text,
  kabul_edilen_adet integer,
  planlanan_bitis_tarihi timestamp with time zone,
  fire_adet integer DEFAULT 0,
  baslama_tarihi timestamp with time zone,
  hedef_adet integer DEFAULT 0,
  fire_dusulmus_adet integer DEFAULT 0,
  firma_id uuid NOT NULL,
  CONSTRAINT yikama_atamalari_pkey PRIMARY KEY (id),
  CONSTRAINT yikama_atamalari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id),
  CONSTRAINT yikama_atamalari_atanan_kullanici_id_fkey FOREIGN KEY (atanan_kullanici_id) REFERENCES auth.users(id),
  CONSTRAINT fk_yikama_atamalari_tedarikci FOREIGN KEY (tedarikci_id) REFERENCES public.tedarikciler(id),
  CONSTRAINT yikama_atamalari_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.yikama_beden_takip (
  id integer NOT NULL DEFAULT nextval('yikama_beden_takip_id_seq'::regclass),
  atama_id integer NOT NULL,
  model_id uuid NOT NULL,
  beden_kodu character varying NOT NULL,
  hedef_adet integer NOT NULL DEFAULT 0,
  uretilen_adet integer DEFAULT 0,
  kabul_edilen_adet integer DEFAULT 0,
  fire_adet integer DEFAULT 0,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  guncelleme_tarihi timestamp with time zone DEFAULT now(),
  CONSTRAINT yikama_beden_takip_pkey PRIMARY KEY (id),
  CONSTRAINT yikama_beden_takip_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.triko_takip(id)
);
CREATE TABLE public.yukleme_kayitlari (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  model_id text,
  adet integer NOT NULL,
  tarih date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  kaynak character varying DEFAULT 'manual'::character varying,
  ceki_id text,
  firma_id uuid NOT NULL,
  CONSTRAINT yukleme_kayitlari_pkey PRIMARY KEY (id),
  CONSTRAINT yukleme_kayitlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id)
);