-- Workflow transition transaction and idempotency helpers
-- Run this migration in Supabase SQL editor before enabling app-side RPC flow.

CREATE TABLE IF NOT EXISTS public.workflow_transition_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firma_id text NOT NULL,
  table_name text NOT NULL,
  record_id bigint NOT NULL,
  from_status text,
  to_status text NOT NULL,
  idempotency_key text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_workflow_transition_idempotency
  ON public.workflow_transition_log (firma_id, table_name, record_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

ALTER TABLE public.kalite_kontrol_atamalari
  ADD COLUMN IF NOT EXISTS kaynak_atama_tablosu text,
  ADD COLUMN IF NOT EXISTS kaynak_atama_id bigint,
  ADD COLUMN IF NOT EXISTS idempotency_key text;

CREATE UNIQUE INDEX IF NOT EXISTS uq_kalite_kontrol_idempotency
  ON public.kalite_kontrol_atamalari (firma_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

ALTER TABLE public.sevkiyat_kayitlari
  ADD COLUMN IF NOT EXISTS kaynak_atama_tablosu text,
  ADD COLUMN IF NOT EXISTS kaynak_atama_id bigint,
  ADD COLUMN IF NOT EXISTS idempotency_key text;

CREATE UNIQUE INDEX IF NOT EXISTS uq_sevkiyat_idempotency
  ON public.sevkiyat_kayitlari (firma_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE OR REPLACE FUNCTION public.apply_workflow_transition(
  p_table_name text,
  p_record_id bigint,
  p_firma_id text,
  p_from_status text,
  p_to_status text,
  p_idempotency_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_status text;
  v_now timestamptz := now();
  v_allowed boolean := false;
  v_has_column boolean;
  v_result jsonb;
BEGIN
  IF p_table_name IS NULL OR trim(p_table_name) = '' THEN
    RAISE EXCEPTION 'table_name zorunlu';
  END IF;

  IF p_to_status IS NULL OR trim(p_to_status) = '' THEN
    RAISE EXCEPTION 'to_status zorunlu';
  END IF;

  IF p_idempotency_key IS NOT NULL THEN
    IF EXISTS (
      SELECT 1
      FROM public.workflow_transition_log
      WHERE firma_id = p_firma_id
        AND table_name = p_table_name
        AND record_id = p_record_id
        AND idempotency_key = p_idempotency_key
    ) THEN
      RETURN jsonb_build_object('applied', false, 'reason', 'idempotent_skip');
    END IF;
  END IF;

  EXECUTE format(
    'SELECT durum FROM public.%I WHERE id = $1 AND firma_id::text = $2 LIMIT 1',
    p_table_name
  ) INTO v_current_status USING p_record_id, p_firma_id;

  IF v_current_status IS NULL THEN
    RAISE EXCEPTION 'Kayit bulunamadi: %.%', p_table_name, p_record_id;
  END IF;

  IF p_from_status IS NOT NULL AND p_from_status <> '' AND v_current_status <> p_from_status THEN
    RAISE EXCEPTION 'Durum uyusmazligi: beklenen %, mevcut %', p_from_status, v_current_status;
  END IF;

  IF v_current_status = p_to_status THEN
    v_allowed := true;
  ELSIF v_current_status IN ('bekleyen', 'beklemede', 'atandi', 'kontrol_bekliyor')
      AND p_to_status IN ('onaylandi', 'kabul_edildi', 'baslandi', 'uretimde', 'reddedildi', 'iptal') THEN
    v_allowed := true;
  ELSIF v_current_status IN ('onaylandi', 'kabul_edildi')
      AND p_to_status IN ('uretimde', 'baslatildi', 'baslandi', 'kismi_tamamlandi', 'tamamlandi', 'reddedildi') THEN
    v_allowed := true;
  ELSIF v_current_status IN ('uretimde', 'baslatildi', 'baslandi', 'devam_ediyor', 'kontrolde', 'sevk_ediliyor', 'kismen_sevk')
      AND p_to_status IN ('kismi_tamamlandi', 'tamamlandi', 'reddedildi', 'kontrolde', 'sevk_ediliyor', 'kismen_sevk') THEN
    v_allowed := true;
  ELSIF v_current_status = 'kismi_tamamlandi'
      AND p_to_status IN ('uretimde', 'baslatildi', 'kismi_tamamlandi', 'tamamlandi', 'reddedildi') THEN
    v_allowed := true;
  ELSIF v_current_status IN ('reddedildi', 'kalite_red')
      AND p_to_status IN ('bekleyen', 'onaylandi') THEN
    v_allowed := true;
  ELSIF v_current_status IN ('tamamlandi', 'sevk_edildi')
      AND p_to_status IN ('onaylandi', 'uretimde') THEN
    v_allowed := true;
  END IF;

  IF NOT v_allowed THEN
    RAISE EXCEPTION 'Gecersiz durum gecisi: % -> %', v_current_status, p_to_status;
  END IF;

  EXECUTE format(
    'UPDATE public.%I SET durum = $1, updated_at = $2 WHERE id = $3 AND firma_id::text = $4',
    p_table_name
  ) USING p_to_status, v_now, p_record_id, p_firma_id;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = p_table_name
      AND column_name = 'onay_tarihi'
  ) INTO v_has_column;

  IF v_has_column AND p_to_status IN ('onaylandi', 'kabul_edildi') THEN
    EXECUTE format(
      'UPDATE public.%I SET onay_tarihi = $1 WHERE id = $2 AND firma_id::text = $3',
      p_table_name
    ) USING v_now, p_record_id, p_firma_id;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = p_table_name
      AND column_name = 'uretim_baslangic_tarihi'
  ) INTO v_has_column;

  IF v_has_column AND p_to_status IN ('uretimde', 'baslatildi', 'baslandi') THEN
    EXECUTE format(
      'UPDATE public.%I SET uretim_baslangic_tarihi = COALESCE(uretim_baslangic_tarihi, $1) WHERE id = $2 AND firma_id::text = $3',
      p_table_name
    ) USING v_now, p_record_id, p_firma_id;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = p_table_name
      AND column_name = 'tamamlama_tarihi'
  ) INTO v_has_column;

  IF v_has_column AND p_to_status IN ('tamamlandi', 'sevk_edildi') THEN
    EXECUTE format(
      'UPDATE public.%I SET tamamlama_tarihi = $1 WHERE id = $2 AND firma_id::text = $3',
      p_table_name
    ) USING v_now, p_record_id, p_firma_id;
  END IF;

  INSERT INTO public.workflow_transition_log (
    firma_id,
    table_name,
    record_id,
    from_status,
    to_status,
    idempotency_key
  ) VALUES (
    p_firma_id,
    p_table_name,
    p_record_id,
    v_current_status,
    p_to_status,
    p_idempotency_key
  );

  v_result := jsonb_build_object(
    'applied', true,
    'from_status', v_current_status,
    'to_status', p_to_status,
    'record_id', p_record_id,
    'table_name', p_table_name
  );

  RETURN v_result;
END;
$$;

NOTIFY pgrst, 'reload schema';
